// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"miniflux-feishu/internal/handlers"
	"miniflux-feishu/internal/services"
)

// Injectors from wire.go:

func InitializeApp() (*gin.Engine, error) {
	feishuService := services.NewFeishuService()
	webhookHandler := handlers.NewWebhookHandler(feishuService)
	engine := NewRouter(webhookHandler)
	return engine, nil
}

// wire.go:

var ProviderSet = wire.NewSet(services.NewFeishuService, handlers.NewWebhookHandler, NewRouter)

func NewRouter(webhookHandler *handlers.WebhookHandler) *gin.Engine {
	return setupRouter(webhookHandler)
}
